export enum errorCodes {
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    BUSINESS_ERROR = "BUSINESS_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    INVALID_TOKEN = "INVALID_TOKEN"
}