export const ROUTES = {
  LOGIN: "Login",
  REGISTER: "Register",
  HOME: "Home",
  EXPENSES: "Expenses",
  CATEGORIAS: "Categorias",
  NOTIFICATIONS: "Notifications",
  SUMMARY: "Summary",
  MAIN_TABS:'MAIN_TABS',
  PROFILE: "Profile",
  EDIT_PROFILE: "EDIT_PROFILE",
  DAADOS_PESSOAIS: "DADOS_PESSOAIS",
  RESUMO_MENSAL: "RESUMO_MENSAL",
  ALTERAR_SENHA: "ALTERAR_SENHA",
} as const;